name: Auto Comment
on:
  issues:
    types:
      - opened
      - closed
      - assigned
  pull_request:
    types:
      - opened
      - closed

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check Author
        id: check_author
        run: echo "Author=${{ github.event.issue.user.login }}"
    
      - name: Auto Comment on Issues Opened
        if: ${{ steps.check_author.outputs.Author != 'Swapnil-Singh-99' && github.actor != github.event.issue.user.login }}
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            ğŸ‘‹ @{{ author }}
            {{steps.check_author.outputs.Author}}
            {{github.actor}}
            {{github.event.issue.user.login}}

            Thank you for raising this issue! We'll look into it ASAP.

            Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š

      - name: Auto Comment on Issues Closed
        if: ${{ steps.check_author.outputs.Author != 'Swapnil-Singh-99' }}
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesClosed: |
            ğŸ‘‹ @{{ author }} This issue is closed.
            Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š

      - name: Auto Comment on Pull Request Merged
        if: ${{ steps.check_author.outputs.Author != 'Swapnil-Singh-99' && github.actor != github.event.issue.user.login }}
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestMerged: |
            ğŸ‘‹ @{{ author }} ğŸ‰ Congrats on your merged pull request! Thanks for the valuable contribution!
            Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š

      - name: Auto Comment on Pull Request Opened
        if: ${{ steps.check_author.outputs.Author != 'Swapnil-Singh-99' && github.actor != github.event.issue.user.login }}
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: |
            HelloğŸ‘‹ @{{ author }}, I hope you are doing well!
            <br>
            Thank you for raising your pull request and contributing to our repository ğŸ‰

            Please make sure you have followed our contributing guidelines. We will review it ASAP.

            Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š

      - name: Auto Comment on Issues Assigned
        if: ${{ steps.check_author.outputs.Author != 'Swapnil-Singh-99' && github.actor != github.event.issue.user.login }}
        uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesAssigned: |
            Hello @{{ author }}, thank you for raising an issue. ğŸ™Œ I have assigned the issue to you. You can now start working on it. If you encounter any problems, please feel free to connect with us. ğŸ‘
            Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š
