name: Auto Comment on Issue and PR Actions

on:
  issues:
    types:
      - opened
      - closed
      - assigned
  pull_request:
    types:
      - opened
      - closed

jobs:
  auto-comment-on-issue-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check Issue/PR Event
        run: "Event: ${{ github.event_name }}"

      - name: Auto Comment on Issue Opened
        if: github.event_name == 'issues' && github.event.action == 'opened' && github.event.issue.user.login != github.repository.owner.login
        run: |
          echo "ğŸ‘‹ @${{ github.event.issue.user.login }}"
          echo ""
          echo "Thank you for raising this issue! We'll look into it ASAP."
          echo "Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Comment on Issue Closed
        if: github.event_name == 'issues' && github.event.action == 'closed'
        run: |
          echo "ğŸ‘‹ @${{ github.event.issue.assignee.login }}"
          echo ""
          echo "This issue is closed."
          echo "Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Comment on Issue Assigned
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        run: |
          echo "Hello @${{ github.event.issue.assignee.login }}, thank you for raising an issue. ğŸ™Œ I have assigned the issue to you. You can now start working on it. If you encounter any problems, please feel free to connect with us. ğŸ‘"
          echo "Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Comment on PR Opened
        if: github.event_name == 'pull_request' && github.event.action == 'opened' && github.event.pull_request.user.login != github.repository.owner.login
        run: |
          echo "HelloğŸ‘‹ @${{ github.event.pull_request.user.login }}, I hope you are doing well!"
          echo ""
          echo "Thank you for raising your pull request and contributing to our repository ğŸ‰"
          echo ""
          echo "Please make sure you have followed our contributing guidelines. We will review it ASAP."
          echo ""
          echo "Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto Comment on PR Merged
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged
        run: |
          echo "ğŸ‘‹ @${{ github.event.pull_request.user.login }} ğŸ‰ Congrats on your merged pull request! Thanks for the valuable contribution!"
          echo "Don't forget to give a â­ï¸ & Happy coding!. ğŸ˜Š"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
